"""empty message

Revision ID: 3dd0d42d6792
Revises: 4baa12ccff54
Create Date: 2025-02-10 18:55:55.962430

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3dd0d42d6792'
down_revision = '4baa12ccff54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
