"""Set card front and back fields to 3000 characters

Revision ID: b4ecf0537706
Revises: 68900486b18c
Create Date: 2025-02-22 16:35:50.501753

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b4ecf0537706'
down_revision = '68900486b18c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'front',
        type_=sqlmodel.sql.sqltypes.AutoString(length=3000),
        existing_type=sa.String(),
        existing_nullable=False)
    op.alter_column('card', 'back',
        type_=sqlmodel.sql.sqltypes.AutoString(length=3000),
        existing_type=sa.String(),
        existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'front',
        type_=sa.String(),
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=3000),
        existing_nullable=False)
    op.alter_column('card', 'back',
        type_=sa.String(),
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=3000),
        existing_nullable=False)
    # ### end Alembic commands ###
