FROM python:3.12

ENV PYTHONUNBUFFERED=1

WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./src /code/src
COPY ./alembic.ini /code/alembic.ini
COPY ./entrypoint.sh /code/entrypoint.sh
COPY ./prestart.sh /code/prestart.sh

RUN chmod +x /code/entrypoint.sh
RUN chmod +x /code/prestart.sh

ENTRYPOINT ["sh", "/code/entrypoint.sh"]
