// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type Card = {
  front: string
  back: string
  id: string
  collection_id: string
}

export type CardCreate = {
  front: string
  back: string
}

export type CardList = {
  data: Array<Card>
  count: number
}

export type CardUpdate = {
  front?: string | null
  back?: string | null
}

export type Collection = {
  name: string
  id: string
  user_id: string
  cards: Array<Card>
}

export type CollectionCreate = {
  name: string
  prompt?: string | null
}

export type CollectionList = {
  data: Array<Collection>
  count: number
}

export type CollectionUpdate = {
  name?: string | null
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type PracticeCard = {
  card_id: string
  id: string
  session_id: string
  is_correct: boolean | null
  is_practiced: boolean
  created_at: string
  updated_at: string
}

export type PracticeCardListResponse = {
  data: Array<PracticeCardResponse>
  count: number
}

export type PracticeCardResponse = {
  card: Card
  is_practiced: boolean
  is_correct: boolean | null
}

export type PracticeCardResultPatch = {
  is_correct: boolean
}

export type PracticeSession = {
  collection_id: string
  id: string
  user_id: string
  is_completed: boolean
  total_cards: number
  cards_practiced: number
  correct_answers: number
  created_at: string
  updated_at: string
  practice_cards: Array<PracticeCard>
}

export type PracticeSessionCreate = {
  collection_id: string
}

export type PracticeSessionList = {
  data: Array<PracticeSession>
  count: number
}

export type Token = {
  access_token: string
  token_type?: string
}

export type UserPublic = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  id: string
}

export type UserRegister = {
  email: string
  password: string
  full_name?: string | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type FlashcardsReadCollectionsData = {
  limit?: number
  skip?: number
}

export type FlashcardsReadCollectionsResponse = CollectionList

export type FlashcardsCreateCollectionData = {
  requestBody: CollectionCreate
}

export type FlashcardsCreateCollectionResponse = Collection

export type FlashcardsReadCollectionData = {
  collectionId: string
}

export type FlashcardsReadCollectionResponse = Collection

export type FlashcardsUpdateCollectionData = {
  collectionId: string
  requestBody: CollectionUpdate
}

export type FlashcardsUpdateCollectionResponse = Collection

export type FlashcardsDeleteCollectionData = {
  collectionId: string
}

export type FlashcardsDeleteCollectionResponse = void

export type FlashcardsReadCardsData = {
  collectionId: string
  limit?: number
  skip?: number
}

export type FlashcardsReadCardsResponse = CardList

export type FlashcardsCreateCardData = {
  collectionId: string
  requestBody: CardCreate
}

export type FlashcardsCreateCardResponse = Card

export type FlashcardsReadCardData = {
  cardId: string
  collectionId: string
}

export type FlashcardsReadCardResponse = Card

export type FlashcardsUpdateCardData = {
  cardId: string
  collectionId: string
  requestBody: CardUpdate
}

export type FlashcardsUpdateCardResponse = Card

export type FlashcardsDeleteCardData = {
  cardId: string
  collectionId: string
}

export type FlashcardsDeleteCardResponse = void

export type FlashcardsStartPracticeSessionData = {
  requestBody: PracticeSessionCreate
}

export type FlashcardsStartPracticeSessionResponse = PracticeSession

export type FlashcardsListPracticeSessionsData = {
  limit?: number
  skip?: number
}

export type FlashcardsListPracticeSessionsResponse = PracticeSessionList

export type FlashcardsGetPracticeSessionStatusData = {
  practiceSessionId: string
}

export type FlashcardsGetPracticeSessionStatusResponse = PracticeSession

export type FlashcardsListPracticeCardsData = {
  limit?: number
  order?: "asc" | "desc" | "random" | null
  practiceSessionId: string
  status?: "pending" | "completed" | "all" | null
}

export type FlashcardsListPracticeCardsResponse = PracticeCardListResponse

export type FlashcardsUpdatePracticeCardResultData = {
  cardId: string
  practiceSessionId: string
  requestBody: PracticeCardResultPatch
}

export type FlashcardsUpdatePracticeCardResultResponse = PracticeCardResponse

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type UsersReadUserMeResponse = UserPublic

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic
