/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutCollectionsIndexImport } from './routes/_layout/collections/index'
import { Route as LayoutCollectionsCollectionIdIndexImport } from './routes/_layout/collections/$collectionId/index'
import { Route as LayoutCollectionsCollectionIdPracticeImport } from './routes/_layout/collections/$collectionId/practice'
import { Route as LayoutCollectionsCollectionIdCardsNewImport } from './routes/_layout/collections/$collectionId/cards/new'
import { Route as LayoutCollectionsCollectionIdCardsCardIdImport } from './routes/_layout/collections/$collectionId/cards/$cardId'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutCollectionsIndexRoute = LayoutCollectionsIndexImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCollectionsCollectionIdIndexRoute =
  LayoutCollectionsCollectionIdIndexImport.update({
    id: '/collections/$collectionId/',
    path: '/collections/$collectionId/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutCollectionsCollectionIdPracticeRoute =
  LayoutCollectionsCollectionIdPracticeImport.update({
    id: '/collections/$collectionId/practice',
    path: '/collections/$collectionId/practice',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutCollectionsCollectionIdCardsNewRoute =
  LayoutCollectionsCollectionIdCardsNewImport.update({
    id: '/collections/$collectionId/cards/new',
    path: '/collections/$collectionId/cards/new',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutCollectionsCollectionIdCardsCardIdRoute =
  LayoutCollectionsCollectionIdCardsCardIdImport.update({
    id: '/collections/$collectionId/cards/$cardId',
    path: '/collections/$collectionId/cards/$cardId',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/collections/': {
      id: '/_layout/collections/'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof LayoutCollectionsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/collections/$collectionId/practice': {
      id: '/_layout/collections/$collectionId/practice'
      path: '/collections/$collectionId/practice'
      fullPath: '/collections/$collectionId/practice'
      preLoaderRoute: typeof LayoutCollectionsCollectionIdPracticeImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/collections/$collectionId/': {
      id: '/_layout/collections/$collectionId/'
      path: '/collections/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof LayoutCollectionsCollectionIdIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/collections/$collectionId/cards/$cardId': {
      id: '/_layout/collections/$collectionId/cards/$cardId'
      path: '/collections/$collectionId/cards/$cardId'
      fullPath: '/collections/$collectionId/cards/$cardId'
      preLoaderRoute: typeof LayoutCollectionsCollectionIdCardsCardIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/collections/$collectionId/cards/new': {
      id: '/_layout/collections/$collectionId/cards/new'
      path: '/collections/$collectionId/cards/new'
      fullPath: '/collections/$collectionId/cards/new'
      preLoaderRoute: typeof LayoutCollectionsCollectionIdCardsNewImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutCollectionsIndexRoute: typeof LayoutCollectionsIndexRoute
  LayoutCollectionsCollectionIdPracticeRoute: typeof LayoutCollectionsCollectionIdPracticeRoute
  LayoutCollectionsCollectionIdIndexRoute: typeof LayoutCollectionsCollectionIdIndexRoute
  LayoutCollectionsCollectionIdCardsCardIdRoute: typeof LayoutCollectionsCollectionIdCardsCardIdRoute
  LayoutCollectionsCollectionIdCardsNewRoute: typeof LayoutCollectionsCollectionIdCardsNewRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCollectionsIndexRoute: LayoutCollectionsIndexRoute,
  LayoutCollectionsCollectionIdPracticeRoute:
    LayoutCollectionsCollectionIdPracticeRoute,
  LayoutCollectionsCollectionIdIndexRoute:
    LayoutCollectionsCollectionIdIndexRoute,
  LayoutCollectionsCollectionIdCardsCardIdRoute:
    LayoutCollectionsCollectionIdCardsCardIdRoute,
  LayoutCollectionsCollectionIdCardsNewRoute:
    LayoutCollectionsCollectionIdCardsNewRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/collections': typeof LayoutCollectionsIndexRoute
  '/collections/$collectionId/practice': typeof LayoutCollectionsCollectionIdPracticeRoute
  '/collections/$collectionId': typeof LayoutCollectionsCollectionIdIndexRoute
  '/collections/$collectionId/cards/$cardId': typeof LayoutCollectionsCollectionIdCardsCardIdRoute
  '/collections/$collectionId/cards/new': typeof LayoutCollectionsCollectionIdCardsNewRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/collections': typeof LayoutCollectionsIndexRoute
  '/collections/$collectionId/practice': typeof LayoutCollectionsCollectionIdPracticeRoute
  '/collections/$collectionId': typeof LayoutCollectionsCollectionIdIndexRoute
  '/collections/$collectionId/cards/$cardId': typeof LayoutCollectionsCollectionIdCardsCardIdRoute
  '/collections/$collectionId/cards/new': typeof LayoutCollectionsCollectionIdCardsNewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_layout/collections/': typeof LayoutCollectionsIndexRoute
  '/_layout/collections/$collectionId/practice': typeof LayoutCollectionsCollectionIdPracticeRoute
  '/_layout/collections/$collectionId/': typeof LayoutCollectionsCollectionIdIndexRoute
  '/_layout/collections/$collectionId/cards/$cardId': typeof LayoutCollectionsCollectionIdCardsCardIdRoute
  '/_layout/collections/$collectionId/cards/new': typeof LayoutCollectionsCollectionIdCardsNewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/signup'
    | '/collections'
    | '/collections/$collectionId/practice'
    | '/collections/$collectionId'
    | '/collections/$collectionId/cards/$cardId'
    | '/collections/$collectionId/cards/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/signup'
    | '/collections'
    | '/collections/$collectionId/practice'
    | '/collections/$collectionId'
    | '/collections/$collectionId/cards/$cardId'
    | '/collections/$collectionId/cards/new'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/signup'
    | '/_layout/collections/'
    | '/_layout/collections/$collectionId/practice'
    | '/_layout/collections/$collectionId/'
    | '/_layout/collections/$collectionId/cards/$cardId'
    | '/_layout/collections/$collectionId/cards/new'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/login",
        "/signup"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/collections/",
        "/_layout/collections/$collectionId/practice",
        "/_layout/collections/$collectionId/",
        "/_layout/collections/$collectionId/cards/$cardId",
        "/_layout/collections/$collectionId/cards/new"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/_layout/collections/": {
      "filePath": "_layout/collections/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/collections/$collectionId/practice": {
      "filePath": "_layout/collections/$collectionId/practice.tsx",
      "parent": "/_layout"
    },
    "/_layout/collections/$collectionId/": {
      "filePath": "_layout/collections/$collectionId/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/collections/$collectionId/cards/$cardId": {
      "filePath": "_layout/collections/$collectionId/cards/$cardId.tsx",
      "parent": "/_layout"
    },
    "/_layout/collections/$collectionId/cards/new": {
      "filePath": "_layout/collections/$collectionId/cards/new.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
