name: Test Backend

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true
      - name: Rename env file
        run : mv .env.example .env
        working-directory: backend
      - run: docker compose -f docker-compose.test.yml down -v --remove-orphans
        working-directory: backend
      - run: docker compose -f docker-compose.test.yml up -d db
        working-directory: backend
      - name: Setup environment
        run: uv run bash prestart.sh
        working-directory: backend
      - name: Run tests
        run: uv run bash tests-start.sh "Coverage for ${{ github.sha }}"
        working-directory: backend
      - run: docker compose -f docker-compose.test.yml down -v --remove-orphans
        working-directory: backend
      - name: Store coverage files
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: backend/htmlcov
          include-hidden-files: true
